version: "3.1"

services:
  php:
    build: .
    container_name: php
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    links:
      - db
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    restart: always
    volumes:
      - /var/lib/mysql
      - ./dbinitial/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=movies_catalog
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=123