version: "3.1"

services:
  db:
    image: mysql
    command: --innodb-use-native-aio=0
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      # - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=movies
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=123